### PR TITLE
new design

### PR DESCRIPTION
**Pull request by romanu417**

### CODE REVIEW

**Comment by mkjsix** [comment]
@romanu417 I'll try to resolve the conflicts myself, strange because you should see conflicts on your side also

**Comment by mkjsix** [comment]
Actually I see too many conflicts. Does the site runs for you locally?

**Comment by romanu417** [comment]
Yes, it works

**Comment by mkjsix** [comment]
It means you didn't merge your local copy with the updated master, otherwise you must see exactly the same conflicts as you can see in this PR

**Comment by romanu417** [comment]
[https://prnt.sc/k5xhfi](https://prnt.sc/k5xhfi)
Can you resolve conflicts because I do not have access?

**Comment by romanu417** [comment]
All is well done?

**Comment by mkjsix** [comment]
@romanu417 yes thanks, merge is successful, we are reviewing the site locally. We'll go back to you with comments as soon as possible.

**Pull request merged**
